const TEAM_ALIASES: Record<string, string> = {
  usa: 'United States',
  'united states': 'United States',
  'south korea': 'South Korea',
  'korea republic': 'South Korea',
  korea: 'South Korea',
  'germany fr': 'Germany',
  'west germany': 'West Germany',
  'german democratic republic': 'East Germany',
  'east germany': 'East Germany',
  russia: 'Russia',
  'soviet union': 'Soviet Union',
  ussr: 'Soviet Union',
  czechoslovakia: 'Czechoslovakia',
  yugoslavia: 'Yugoslavia',
  'serbia and montenegro': 'Serbia and Montenegro',
  'fr yugoslavia': 'Yugoslavia',
  'ir iran': 'Iran',
  "cote d'ivoire": 'Ivory Coast',
  'côte d\'ivoire': 'Ivory Coast',
  'republic of ireland': 'Ireland',
  'northern ireland': 'Northern Ireland',
  'bosnia-herzegovina': 'Bosnia and Herzegovina',
  'bosnia and herzegovina': 'Bosnia and Herzegovina',
  'trinidad and tobago': 'Trinidad and Tobago',
  'costa rica': 'Costa Rica',
  'saudi arabia': 'Saudi Arabia',
  'south africa': 'South Africa',
  'new zealand': 'New Zealand',
  'north korea': 'North Korea',
  'korea dpr': 'North Korea',
  'dutch east indies': 'Dutch East Indies',
  'indias orientais holandesas': 'Dutch East Indies',
  'índias orientais holandesas': 'Dutch East Indies',
  'united arab emirates': 'United Arab Emirates',
  'el salvador': 'El Salvador',
  'czech republic': 'Czech Republic',
}

const CANONICAL_CODES: Record<string, string> = {
  'United States': 'USA',
  'South Korea': 'KOR',
  Germany: 'GER',
  'West Germany': 'FRG',
  'East Germany': 'GDR',
  'Soviet Union': 'URS',
  Russia: 'RUS',
  Czechoslovakia: 'TCH',
  Yugoslavia: 'YUG',
  Brazil: 'BRA',
  Argentina: 'ARG',
  Uruguay: 'URU',
  France: 'FRA',
  Italy: 'ITA',
  Spain: 'ESP',
  England: 'ENG',
  Netherlands: 'NED',
  Mexico: 'MEX',
  Portugal: 'POR',
  Belgium: 'BEL',
  Croatia: 'CRO',
  Morocco: 'MAR',
  Japan: 'JPN',
  Switzerland: 'SUI',
  Sweden: 'SWE',
  Poland: 'POL',
  Colombia: 'COL',
  Chile: 'CHI',
  Peru: 'PER',
  Ecuador: 'ECU',
  Denmark: 'DEN',
  Australia: 'AUS',
  Cameroon: 'CMR',
  Ghana: 'GHA',
  Senegal: 'SEN',
  Nigeria: 'NGA',
  'Costa Rica': 'CRC',
  'Saudi Arabia': 'KSA',
  Iran: 'IRN',
  Wales: 'WAL',
  Scotland: 'SCO',
  Hungary: 'HUN',
  Austria: 'AUT',
  'Czech Republic': 'CZE',
  Serbia: 'SRB',
  Turkey: 'TUR',
  Ukraine: 'UKR',
  Romania: 'ROU',
  Bulgaria: 'BUL',
  Paraguay: 'PAR',
  'Ivory Coast': 'CIV',
  Tunisia: 'TUN',
  Algeria: 'ALG',
  'South Africa': 'RSA',
  'New Zealand': 'NZL',
  'North Korea': 'PRK',
  Canada: 'CAN',
  Panama: 'PAN',
  Iceland: 'ISL',
  'Bosnia and Herzegovina': 'BIH',
  Ireland: 'IRL',
  'Northern Ireland': 'NIR',
  'Trinidad and Tobago': 'TRI',
  China: 'CHN',
  'El Salvador': 'SLV',
  Haiti: 'HAI',
  Zaire: 'ZAI',
  'DR Congo': 'COD',
  Kuwait: 'KUW',
  Iraq: 'IRQ',
  'United Arab Emirates': 'UAE',
  Bolivia: 'BOL',
  Honduras: 'HON',
  Jamaica: 'JAM',
  Qatar: 'QAT',
  Togo: 'TOG',
  Angola: 'ANG',
  Slovenia: 'SVN',
  Slovakia: 'SVK',
  Greece: 'GRE',
  Egypt: 'EGY',
  Israel: 'ISR',
  Norway: 'NOR',
  Cuba: 'CUB',
  'Dutch East Indies': 'IDN',
  'Serbia and Montenegro': 'SCG',
}

const TEAM_NAMES_PT: Record<string, string> = {
  Algeria: 'Argélia',
  Angola: 'Angola',
  Argentina: 'Argentina',
  Australia: 'Austrália',
  Austria: 'Áustria',
  Belgium: 'Bélgica',
  Bolivia: 'Bolívia',
  'Bosnia and Herzegovina': 'Bósnia e Herzegovina',
  Brazil: 'Brasil',
  Bulgaria: 'Bulgária',
  Cameroon: 'Camarões',
  Canada: 'Canadá',
  Chile: 'Chile',
  China: 'China',
  Colombia: 'Colômbia',
  'Costa Rica': 'Costa Rica',
  Croatia: 'Croácia',
  Cuba: 'Cuba',
  'Czech Republic': 'República Tcheca',
  Czechoslovakia: 'Tchecoslováquia',
  'Dutch East Indies': 'Índias Orientais Holandesas',
  'East Germany': 'Alemanha Oriental',
  Ecuador: 'Equador',
  Egypt: 'Egito',
  'El Salvador': 'El Salvador',
  England: 'Inglaterra',
  France: 'França',
  Germany: 'Alemanha',
  Ghana: 'Gana',
  Greece: 'Grécia',
  Haiti: 'Haiti',
  Honduras: 'Honduras',
  Hungary: 'Hungria',
  Iceland: 'Islândia',
  Iran: 'Irã',
  Iraq: 'Iraque',
  Ireland: 'Irlanda',
  Israel: 'Israel',
  Italy: 'Itália',
  'Ivory Coast': 'Costa do Marfim',
  Jamaica: 'Jamaica',
  Japan: 'Japão',
  Kuwait: 'Kuwait',
  Mexico: 'México',
  Morocco: 'Marrocos',
  Netherlands: 'Holanda',
  'New Zealand': 'Nova Zelândia',
  Nigeria: 'Nigéria',
  'North Korea': 'Coreia do Norte',
  'Northern Ireland': 'Irlanda do Norte',
  Norway: 'Noruega',
  Panama: 'Panamá',
  Paraguay: 'Paraguai',
  Peru: 'Peru',
  Poland: 'Polônia',
  Portugal: 'Portugal',
  Qatar: 'Catar',
  Romania: 'Romênia',
  Russia: 'Rússia',
  'Saudi Arabia': 'Arábia Saudita',
  Scotland: 'Escócia',
  Senegal: 'Senegal',
  Serbia: 'Sérvia',
  'Serbia and Montenegro': 'Sérvia e Montenegro',
  Slovakia: 'Eslováquia',
  Slovenia: 'Eslovênia',
  'South Africa': 'África do Sul',
  'South Korea': 'Coreia do Sul',
  'Soviet Union': 'União Soviética',
  Spain: 'Espanha',
  Sweden: 'Suécia',
  Switzerland: 'Suíça',
  Togo: 'Togo',
  'Trinidad and Tobago': 'Trinidad e Tobago',
  Tunisia: 'Tunísia',
  Turkey: 'Turquia',
  Ukraine: 'Ucrânia',
  'United Arab Emirates': 'Emirados Árabes Unidos',
  'United States': 'Estados Unidos',
  Uruguay: 'Uruguai',
  Wales: 'País de Gales',
  'West Germany': 'Alemanha Ocidental',
  Yugoslavia: 'Iugoslávia',
  Zaire: 'Zaire',
}

function normalizeKey(value: string): string {
  return value
    .normalize('NFD')
    .replace(/\p{M}/gu, '')
    .trim()
    .toLowerCase()
}

export function canonicalizeTeamName(name: string): string {
  const trimmed = name.trim()
  if (!trimmed) return trimmed

  const alias = TEAM_ALIASES[normalizeKey(trimmed)]
  return alias ?? trimmed
}

export function getHistoricalTeamDisplayName(name: string): string {
  const canonical = canonicalizeTeamName(name)
  return TEAM_NAMES_PT[canonical] ?? canonical
}

export function getTeamCode(name: string, codeFromData?: string | null): string {
  if (codeFromData?.trim()) return codeFromData.trim().toUpperCase()

  const canonical = canonicalizeTeamName(name)
  return CANONICAL_CODES[canonical] ?? canonical.slice(0, 3).toUpperCase()
}

export function syntheticTeamId(name: string): number {
  const canonical = canonicalizeTeamName(name)
  let hash = 0

  for (let index = 0; index < canonical.length; index += 1) {
    hash = (hash * 31 + canonical.charCodeAt(index)) | 0
  }

  return Math.abs(hash) || 1
}
