const LINEUP_POSITION_LABELS: Record<string, string> = {
  goalkeeper: 'Goleiro',
  goalie: 'Goleiro',
  keeper: 'Goleiro',
  gk: 'Goleiro',
  'centre-back': 'Zagueiro',
  'center-back': 'Zagueiro',
  'centre back': 'Zagueiro',
  'center back': 'Zagueiro',
  cb: 'Zagueiro',
  defender: 'Zagueiro',
  df: 'Zagueiro',
  defense: 'Defesa',
  defence: 'Defesa',
  backline: 'Linha de zaga',
  'full-back': 'Lateral',
  'full back': 'Lateral',
  fb: 'Lateral',
  'left-back': 'Lateral esquerdo',
  'left back': 'Lateral esquerdo',
  lb: 'Lateral esquerdo',
  'right-back': 'Lateral direito',
  'right back': 'Lateral direito',
  rb: 'Lateral direito',
  'left wing-back': 'Ala esquerda',
  'left wing back': 'Ala esquerda',
  'right wing-back': 'Ala direita',
  'right wing back': 'Ala direita',
  'wing-back': 'Ala',
  'wing back': 'Ala',
  wb: 'Ala',
  lwb: 'Ala esquerda',
  rwb: 'Ala direita',
  midfielder: 'Meio-campista',
  mf: 'Meio-campista',
  midfield: 'Meio-campista',
  'defensive midfield': 'Volante',
  'defensive midfielder': 'Volante',
  'holding midfield': 'Volante',
  'holding midfielder': 'Volante',
  dm: 'Volante',
  cdm: 'Volante',
  'central midfield': 'Meia central',
  'central midfielder': 'Meia central',
  cm: 'Meia central',
  'attacking midfield': 'Meia-atacante',
  'attacking midfielder': 'Meia-atacante',
  am: 'Meia-atacante',
  cam: 'Meia-atacante',
  playmaker: 'Armador',
  'left midfield': 'Meia esquerda',
  'left midfielder': 'Meia esquerda',
  lm: 'Meia esquerda',
  'right midfield': 'Meia direita',
  'right midfielder': 'Meia direita',
  rm: 'Meia direita',
  forward: 'Atacante',
  fw: 'Atacante',
  attack: 'Ataque',
  offense: 'Ataque',
  offence: 'Ataque',
  striker: 'Centroavante',
  st: 'Centroavante',
  'centre-forward': 'Centroavante',
  'center-forward': 'Centroavante',
  'centre forward': 'Centroavante',
  'center forward': 'Centroavante',
  cf: 'Centroavante',
  'second striker': 'Segundo atacante',
  ss: 'Segundo atacante',
  winger: 'Ponta',
  'left winger': 'Ponta esquerda',
  'left wing': 'Ponta esquerda',
  lw: 'Ponta esquerda',
  'right winger': 'Ponta direita',
  'right wing': 'Ponta direita',
  rw: 'Ponta direita',
  sweeper: 'Líbero',
  coach: 'Técnico',
  manager: 'Técnico',
}

const PARTIAL_POSITION_LABELS: Array<[pattern: string, label: string]> = [
  ['goalkeeper', 'Goleiro'],
  ['goalie', 'Goleiro'],
  ['keeper', 'Goleiro'],
  ['centre-back', 'Zagueiro'],
  ['center-back', 'Zagueiro'],
  ['centre back', 'Zagueiro'],
  ['center back', 'Zagueiro'],
  ['left wing-back', 'Ala esquerda'],
  ['right wing-back', 'Ala direita'],
  ['wing-back', 'Ala'],
  ['wing back', 'Ala'],
  ['left-back', 'Lateral esquerdo'],
  ['left back', 'Lateral esquerdo'],
  ['right-back', 'Lateral direito'],
  ['right back', 'Lateral direito'],
  ['full-back', 'Lateral'],
  ['full back', 'Lateral'],
  ['holding midfield', 'Volante'],
  ['defensive midfield', 'Volante'],
  ['attacking midfield', 'Meia-atacante'],
  ['central midfield', 'Meia central'],
  ['left midfield', 'Meia esquerda'],
  ['right midfield', 'Meia direita'],
  ['playmaker', 'Armador'],
  ['left winger', 'Ponta esquerda'],
  ['right winger', 'Ponta direita'],
  ['left wing', 'Ponta esquerda'],
  ['right wing', 'Ponta direita'],
  ['centre-forward', 'Centroavante'],
  ['center-forward', 'Centroavante'],
  ['centre forward', 'Centroavante'],
  ['center forward', 'Centroavante'],
  ['second striker', 'Segundo atacante'],
  ['striker', 'Centroavante'],
  ['midfielder', 'Meio-campista'],
  ['midfield', 'Meio-campista'],
  ['forward', 'Atacante'],
  ['winger', 'Ponta'],
  ['defender', 'Zagueiro'],
  ['backline', 'Linha de zaga'],
  ['defense', 'Defesa'],
  ['defence', 'Defesa'],
  ['offense', 'Ataque'],
  ['offence', 'Ataque'],
  ['attack', 'Ataque'],
  ['sweeper', 'Líbero'],
]

export function translateLineupPosition(position: string): string {
  const normalized = position.trim()

  if (!normalized) {
    return ''
  }

  const lower = normalized.toLowerCase()
  const exact = LINEUP_POSITION_LABELS[lower]

  if (exact) {
    return exact
  }

  for (const [pattern, label] of PARTIAL_POSITION_LABELS) {
    if (lower.includes(pattern)) {
      return label
    }
  }

  return normalized
}
