const TEAM_NAMES_PT: Record<string, string> = {
  'South Africa': 'África do Sul',
  Germany: 'Alemanha',
  'Saudi Arabia': 'Arábia Saudita',
  Algeria: 'Argélia',
  Argentina: 'Argentina',
  Australia: 'Austrália',
  Austria: 'Áustria',
  Belgium: 'Bélgica',
  'Bosnia-Herzegovina': 'Bósnia e Herzegovina',
  'Bosnia-H.': 'Bósnia e Herzegovina',
  Brazil: 'Brasil',
  'Cape Verde': 'Cabo Verde',
  Canada: 'Canadá',
  Qatar: 'Catar',
  Colombia: 'Colômbia',
  'South Korea': 'Coreia do Sul',
  'Korea Republic': 'Coreia do Sul',
  'Ivory Coast': 'Costa do Marfim',
  Croatia: 'Croácia',
  Curaçao: 'Curaçau',
  Egypt: 'Egito',
  Ecuador: 'Equador',
  Scotland: 'Escócia',
  Spain: 'Espanha',
  'United States': 'Estados Unidos',
  USA: 'Estados Unidos',
  France: 'França',
  Ghana: 'Gana',
  Haiti: 'Haiti',
  Netherlands: 'Holanda',
  England: 'Inglaterra',
  Iran: 'Irã',
  Iraq: 'Iraque',
  Japan: 'Japão',
  Jordan: 'Jordânia',
  Morocco: 'Marrocos',
  Mexico: 'México',
  Norway: 'Noruega',
  'New Zealand': 'Nova Zelândia',
  Panama: 'Panamá',
  Paraguay: 'Paraguai',
  Portugal: 'Portugal',
  'Congo DR': 'República Democrática do Congo',
  'DR Congo': 'República Democrática do Congo',
  Czechia: 'República Tcheca',
  'Czech Republic': 'República Tcheca',
  Senegal: 'Senegal',
  Sweden: 'Suécia',
  Switzerland: 'Suíça',
  Tunisia: 'Tunísia',
  Turkey: 'Turquia',
  Uruguay: 'Uruguai',
  Uzbekistan: 'Uzbequistão',
}

export function translateTeamName(name: string): string {
  const trimmed = name.trim()
  if (!trimmed) return ''
  return TEAM_NAMES_PT[trimmed] ?? trimmed
}
